import SwiftUI

struct ContentView: View {
    var body: some View {
        ZStack {
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
            Text("X")
                .font(.largeTitle)
                .foregroundColor(.black)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(x: 140, y: 140)
            Text("O")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(x: 140, y: 140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(x: -140, y: 140)
            Text("O")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(x: -140, y: 140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(x: 140, y: -140)
            Text("O")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(x: 140, y: -140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(x: -140, y: -140)
            Text("X")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(x: -140, y: -140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(x: 140)
            Text("X")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(x: 140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(x: -140)
            Text("O")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(x: -140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(y: -140)
            Text("X")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(y: -140)
            Rectangle()
                .fill(Color.blue)
                .frame(width: 120, height: 120)
                .offset(y: 140)
            Text("X")
                .font(.largeTitle)
                .foregroundColor(.black)
                .offset(y: 140)
        }
    }
}
